# Mudamos para o Debian puro para ter mais compatibilidade
FROM debian:latest

# Instalamos as ferramentas que você precisa para o Lab
RUN apt update && apt install -y \
    iputils-ping \
    iproute2 \
    tcpdump \
    traceroute \
    iperf3 \
    curl \
    python3-pip \
    && apt clean && rm -rf /var/lib/apt/lists/*

# Se você quiser manter o Scapy para testes de pacotes:
RUN pip install --break-system-packages scapy

WORKDIR /root
CMD ["bash"]