/** Valid `view` query values for the Phase 2 WebUI shell (single source of truth). */
export const PLATFORM_NAV_VIEW_IDS = new Set<string>([
  "overview",
  "delta-digest",
  "evidence-consistency",
  "stability-workspace",
  "situation-room",
  "operator-briefing",
  "investigation",
  "devices",
  "topology",
  "policies",
  "path-explorer",
  "service-impact-workspace",
  "service-explorer",
  "service-dossier",
  "maintenance-preview",
  "maintenance-evidence-workspace",
  "impact-report",
  "change-safety-case",
  "workflows",
  "audit",
  "capabilities",
  "readiness",
  "platform-health",
  "evidence-replay",
]);
